# Generated by Django 4.2.7 on 2023-11-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizlet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afisha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_title', models.CharField(max_length=100)),
                ('time_watch', models.TimeField()),
                ('area', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FilmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название фильма')),
                ('country', models.CharField(max_length=100, verbose_name='Укажите название страны')),
                ('image', models.ImageField(upload_to='films/')),
                ('genre', models.CharField(choices=[('Horror', 'Horror'), ('Dramma', 'Dramma')], max_length=100)),
                ('director', models.CharField(max_length=100, verbose_name='Укажите директора')),
                ('description', models.TextField(blank=True, verbose_name='Укажите описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
